version: "3.8"

services:
  app:
    container_name: sber_test_app
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    command: bash -c "./entrypoint_api.sh"
    env_file:
      - .env
    volumes:
      - /db_data/db.sqlite3:/db.sqlite3